### ISSUE TITLE
Not being able to test on consumer side, take doesn't propagate termination ???

### ISSUE THREAD

**Issue by jaksky** [akka/reactive-kafka#282] opened 2017-03-23 14:14 UTC
How do we handle testing e.g. producer -> topic -> consumer

```
val source = Consumer.atMostOnceSource(consumerSettings, Subscriptions.topics(testingTopic))
        .map(_.value())
      val value = source.map { r =>
        println("Recieved message " + r)
        r
      } .take(1)
        .runWith(Sink.seq)
      value.futureValue mustBe Seq(testingMSG)
```

Resulting in timing out the future due to not terminating consumer source from take(n).  Or how do we test as I suppose that this is common scenario 
Currently using v.14
Any possible workaround?

**Comment by kciesielski** [comment] 2017-03-24 07:43
@jaksky Consider using Akka TestKit and probes. 
Here are official docs:
http://doc.akka.io/docs/akka/2.4.17/scala/stream/stream-testkit.html#Streams_TestKit
And here's how we use it:
https://github.com/akka/reactive-kafka/blob/7f23dbc189d75d37fe43ee2abd4624a8ac9089e8/core/src/test/scala/akka/kafka/scaladsl/IntegrationSpec.scala#L170

Anyway, using `take` should terminate should close the stream. How long is your test waiting for the timeout? Maybe adding `with IntegrationPatience` to mixed traits would help?

**Comment by ksilin** [comment] 2017-08-09 15:37
related/duplicate of https://github.com/akka/reactive-kafka/issues/166

**Comment by 2m** [comment] 2018-06-12 12:44
Closing as a duplicate of #166

**Closed by 2m** 2018-06-12 12:44 UTC
