### ISSUE TITLE
multiple bootstrap servers

### ISSUE THREAD

**Issue by rukbrook** [akka/reactive-kafka#417] opened 2018-03-16 10:28 UTC
Is it possible with the akka stream kafka to set the bootstrap servers with an array of values? When I set 1 bootstrap server, everything works as it should, if I add more to the config file (for example: akka.kafka.consumer.kafka-clients.bootstrap.servers = server1:port, server2:port, server3:port) I get the following errors:

`[WARN] [03/15/2018 15:23:53.335] [kafkaConsumer_testOPTIN_666f7120-e14e-1004-8230-3a221e9ce4d4-akka.kafka.default-dispatcher-12] [akka://kafkaConsumer_testOPTIN_666f7120-e14e-1004-8230-3a221e9ce4d4/system/kafka-consumer-1] Consumer interrupted with WakeupException after timeout. Message: null. Current value of akka.kafka.consumer.wakeup-timeout is 30000 milliseconds`

If it's possible to use multiple bootstrap servers how akka-kafka lib works with them? If their client-side fault tolerance and/or load balancing assumed?

**Comment by ennru** [comment] 2018-05-17 14:15
The value from `bootstrap.servers` is passed on to the Kafka property `ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG` as described in the [Kafka documentation](http://kafka.apache.org/documentation/#newconsumerconfigs) without any interference.
So your approach is expected to work.
I get a warning `Connection to node -2 could not be established. Broker may not be available.` when I add a second non-existing address.

**Comment by TimMoore** [comment] 2018-05-17 23:33
I can confirm that passing a comma-separated list of broker endpoints as a string does work.

What does not work is using the HOCON array syntax (because that doesn't flatten down to a comma-separated string, but a list of indexed property keys that the Kafka client knows nothing about).

**Comment by ennru** [comment] 2018-05-30 12:27
As confirmed by @TimMoore this does work, closing this issue.

**Closed by ennru** 2018-05-30 12:27 UTC
