### ISSUE TITLE
Producer infrastructure should be implemented as simple a function => Future instead of as a stage

### ISSUE THREAD

**Issue by jrudolph** [akka/reactive-kafka#344] opened 2017-09-26 12:04 UTC
It doesn't seem to provide anything over mapAsync. Also, given the current API it is impossible to ignore single failing messages without failing the whole stream.

**Comment by iravid** [comment] 2017-09-26 12:28
There are benefits for managing the initialization/shutdown of the producer along with the stream lifecycle in case the producer is not shared with other streams, but it is recommended to share it to improve throughput anyway.

I agree, anyway :-) Wrote about this here: https://www.iravid.com/posts/using-cats-with-reactive-kafka.html

**Comment by johanandren** [comment] 2017-12-15 07:58
Duplicate of or related to: #250

**Comment by 2m** [comment] 2018-06-12 12:36
Producer stage is a bit more complicated now because of the handling of multi-messages. Therefore it will not be possible to implement it using only `mapAsync`.

**Closed by 2m** 2018-06-12 12:36 UTC
Labels: enhancement, obsolete - reopen if neccessary
