### ISSUE TITLE
add more integration tests

### ISSUE THREAD

**Issue by patriknw** [akka/reactive-kafka#125] opened 2016-04-01 12:30 UTC

**Comment by patriknw** [comment] 2016-04-01 12:30
https://github.com/akka/reactive-kafka/blob/master/core/src/test/scala/akka/kafka/scaladsl/IntegrationSpec.scala

**Comment by nafshartous** [comment] 2016-05-12 13:32
@patriknw  I'd like to see if I can help.  Did you have any specific test cases in mind ?

**Comment by patriknw** [comment] 2016-05-12 13:38
That help is very much appreciated.
It's very thin at the moment so any scenario you can think of would be great addition. You can perhaps get inspiration from the examples, and port some of those scenarios overt to tests. https://github.com/akka/reactive-kafka/tree/master/core/src/test/scala/examples

**Comment by nafshartous** [comment] 2016-05-23 15:54
@patriknw  I've reviewed the examples against the current integration tests so as not to overlap.  
Seems like the examples where the producer batches could be ported.  Was also wondering about testing any behaviour specific to the producer batching.  For instance, does the batching cause a delay in messages being visible to a consumer ?

**Comment by patriknw** [comment] 2016-05-24 11:15
Note that the examples are not tested, so feel free to copy them to an integration test also where it makes sense.

batching is for the commits to the consumer, right?
e.g. you consume msg 1, 2,.. 10, and then commit all of them in one batch instead of one-by-one.
Such a tests should verify that when restarting the consumer it will see 11 as first message.

**Comment by nafshartous** [comment] 2016-05-30 17:34
I have this in progress on a local branch (nafshartous-125).  Would I be given write permission at some point to push the branch in order to create a pull request ?

**Comment by patriknw** [comment] 2016-05-30 17:48
@nafshartous That is great. Please create a fork in your github account and then you can submit a pull request from your fork to akka/reactive-kafka

**Comment by nafshartous** [comment] 2016-06-12 14:38
Here's an update.  I've added two tests to IntegrationSpec.scala on my fork based on some of the batching examples

```
   https://github.com/nafshartous/reactive-kafka/tree/master/core/src/test/scala/akka/kafka/scaladsl
```

and have a few questions if anyone could provide input.  On successive test runs I'm seeing javax.management.InstanceAlreadyExistsExceptio\
n: kafka.consumer:type=app-info,id=client1-43172491-b8a8-4429-b5b5-27f02e7f0983  This does not seem to affect the tests though maybe something needs to done on test tear down ?

The last test connects a consumer (consuming from topic1) to a producer (producing to topic2) and is unstable with the following issues

    * The println("connect message: " + msg.value); only prints up to 87, so I was curious why
      the output is not going up to 100 ?

    * As-is (with the commented block) the first run fails while waiting for OnNext(1) and then successive runs pass.

    * The commented part at the end (probing topic2) fails

```
    [info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for OnNext(1)
```
    It may be a timing issues because if a sleep is inserted before probing then sometimes the error message indicates

```
        while waiting for OnNext(72)
```

   Thanks for any suggestion on what to do with this test.

**Comment by nafshartous** [comment] 2016-06-16 14:10
Also, if there are any useful API's for debugging and examining the state of Kafka I could dig into the intermittent failures further.

**Comment by nafshartous** [comment] 2016-06-18 00:55
Resolved the failures and created a pull request (https://github.com/akka/reactive-kafka/pull/159)

**Comment by nafshartous** [comment] 2016-07-07 02:50
@13h3r  Following up on two open issues from the two new tests.

I tried to use ```Sink.ignore``` as you suggested to create a ```Future```
```
 def produceMessages(topic: String, range: Range) = {
    Source(range)
      .map(n => new ProducerRecord(topic, partition0, null: Array[Byte], n.toString))
      .via(Producer.flow(producerSettings))
      .toMat(Sink.ignore)(Keep.right)
```
however the types don't work out.  The error is found ```Flow``` required ```Graph```.

**Comment by nafshartous** [comment] 2016-07-07 02:56
The second is regarding function ```consumeAndBatchCommit```, specifically how to know when the stream can be cancelled in the presence of batching ?

**Comment by patriknw** [comment] 2016-07-07 08:56
what if you try to add explicit return type for the `Future` (always a good idea anyway)

**Comment by nafshartous** [comment] 2016-08-02 00:29
I've added code to return a `Future` when producing messages.  Upon checking the `Future` with `onComplete` the `Failure` case is triggered (error message below).  Was wondering what might cause the "unknown operation / terminated abruptly" error.

Error producing messages: 1 to 100 - Processor actor [Actor[akka://IntegrationSpec/user/StreamSupervisor-0/flow-0-2-unknown-operation#-311663728]] terminated abruptly

The code is on my fork:

https://github.com/nafshartous/reactive-kafka/blob/a9efa8f4ff39c317c8d34dbaa615e16fd083a360/core/src/test/scala/akka/kafka/scaladsl/IntegrationSpec.scala

in method `produceAndConsume`.

**Comment by drewhk** [comment] 2016-08-02 08:17
My guess is that you simply stop the actor system before the test fully completes and hence the stream is forced to fail (the system which executes it stops).

**Comment by nafshartous** [comment] 2016-08-03 02:00
Thanks @drewhk, seems like the end of the test was implicitly stopping the actor system.  Was trying to avoid using ```Await``` thought it seems necessary.

**Comment by nafshartous** [comment] 2016-08-17 00:37
I'm trying to fix some issues related to the batching tests and have a question.
After producing the sequence 1..100 and then using a batching consumer, i.e.

```
def consumeAndBatchCommit(topic: String) = {
        Consumer.committableSource(consumerSettings, TopicSubscription(Set(topic)))
          .map { msg => { ; msg.committableOffset } }
          .batch(max = 10, first => CommittableOffsetBatch.empty.updated(first)) { (batch, elem) =>
            batch.updated(elem)
          }
          .mapAsync(1)(_.commitScaladsl())
          .toMat(TestSink.probe)(Keep.both).run()
      }
```

and a probe

```
      val (control, probe) = consumeAndBatchCommit(topic1)

      probe.request(100).expectNextN(100)
```

the verification `expectNextN(100)` times out waiting

```
java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsgClass waiting for class akka.stream.testkit.TestSubscriber$OnNext^[[0m^[[0m
```

I assume this has to do with the batching and that its the number of batches visible to the `probe` as opposed the queue elements ?  Just wondering what kind of verification can be done using the `probe` in the context of batching

**Comment by patriknw** [comment] 2016-08-17 07:20
I don't think we should test the actual `batch` combinator. That is done by Akka Streams. I think we should verify that the offset is stored and that we can restart from it. Similar to "resume consumer from committed offset".

**Comment by nafshartous** [comment] 2016-08-28 17:00
I'm not sure how to proceed with my PR

  https://github.com/akka/reactive-kafka/pull/209

The test "consume and commit in batches" passes consistently when run locally
and fails consistently in Travis.

The assertion that's failing is attempting to verify that a batch was committed (line 251)
When inserting a `println` at the point of batch commit and it only prints once (even when requesting multiple batches, not sure why multiple lines are not output).

Thanks for any suggestions.

**Comment by cchantep** [comment] 2017-02-18 15:40
May in some way be related: 

Hi, bootstraping a Kafka project using reactive-kafka, some tests are failing when using the utility `assertAllStagesStopped`. I've created a local branch directly from a fork of reactive-kafka, and it seems this module itself is failing to pass consumer tests with this assertion (see [Test results](https://gist.github.com/cchantep/e74e8ff9f1ae4587f539f294b7b79f5d). I could submit a PR with the tests, then it would be nice if some contributor of this project have a look at it ...

> See [branch with updated tests](https://github.com/cchantep/reactive-kafka/tree/feature/test-stages-stop)

**Comment by kciesielski** [comment] 2017-02-20 08:54
@cchantep Thanks for reporting this. I tried with `akka-stream-contrib` version `0.6` instead of and all tests in `IntegrationSpec` are passing, `ConsumerTests` are failing like in your report. Looking into that now.

**Comment by cchantep** [comment] 2017-02-20 09:35
Even with 0.6, I get the failure with `IntegrationSpec`

**Comment by kciesielski** [comment] 2017-02-20 10:19
@cchantep I managed to close resources correctly in failing tests for the `ConsumerTests` suite. However, I can't reproduce your error from `IntegrationSpec`. Here's my change: https://github.com/kciesielski/reactive-kafka/commit/0af6590f022fc59729f0a0529ddbc8618966eea2, could you apply it and publish a PR so we can see how it goes on CI?

**Comment by cchantep** [comment] 2017-02-20 10:54
I reproduce the issue with `IntegrationSpec` each time, executing it with all the suite or only:

```
[info] - must connect consumer to producer and commit in batches *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected no StreamSupervisor children, but got [Actor[akka://IntegrationSpec/user/StreamSupervisor-0/flow-14-1-unknown-operation#-1759701395]]
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.stream.contrib.TestKit$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TestKit.scala:34)
[info]   at akka.stream.contrib.TestKit$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(TestKit.scala:31)
[info]   at akka.stream.contrib.TestKit$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(TestKit.scala:31)
[info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:303)
[info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:314)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:814)
[info]   at akka.stream.contrib.TestKit$$anonfun$assertAllStagesStopped$1.apply$mcV$sp(TestKit.scala:31)
[info]   at akka.stream.contrib.TestKit$$anonfun$assertAllStagesStopped$1.apply(TestKit.scala:29)
[info]   at akka.stream.contrib.TestKit$$anonfun$assertAllStagesStopped$1.apply(TestKit.scala:29)
```

**Comment by kciesielski** [comment] 2017-02-20 11:23
@cchantep Can you submit a Pull Request with my updates? We will see if this occurs on Travis.

**Comment by cchantep** [comment] 2017-02-20 12:38
https://github.com/akka/reactive-kafka/pull/271

**Comment by ennru** [comment] 2018-06-12 12:08
We added quite a number of new integration test with 0.21.

**Closed by ennru** 2018-06-12 12:08 UTC
Labels: new-api
