### ISSUE TITLE
Consumer crashes when receiving inappropriate data

### ISSUE THREAD

**Issue by brunofitas** [akka/reactive-kafka#132] opened 2016-04-11 15:04 UTC
It looks like the Consumer is crashing when fed with inappropriate data.

To reproduce the issue, create a Consumer with a ByteArrayDeserializer:

```scala
val consumerSettings = {
    ConsumerSettings(context.system, new ByteArrayDeserializer, new ByteArrayDeserializer,
      Set(consumer_topic))
      .withBootstrapServers(kafka_host)
      .withGroupId(group_id)
      .withProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest")
 }
```

Create a producer 

```scala
val producerSettings = {
    ProducerSettings(context.system, new ByteArraySerializer, new ByteArraySerializer)
      .withBootstrapServers("127.0.0.1:9092")
  }
```
Publish a byte array to the topic

```scala
Source.single("Ping".getBytes)
      .map(elem => new ProducerRecord[Array[Byte], Array[Byte]](consumerTopic, elem))
      .to(Producer.plainSink(producerSettings)).run()
```

Everything works fine.
Now, add a producer with a StringSerializer

```scala
val producerSettings2 = {
    ProducerSettings(context.system, new ByteArraySerializer, new StringSerializer)
      .withBootstrapServers("127.0.0.1:9092")
  }
```
and publish a String to the topic

```scala
Source.single("Ping")
      .map(elem => new ProducerRecord[Array[Byte],String](consumerTopic, elem))
      .to(Producer.plainSink(producerSettings2)).run()
```
The Consumer will stop working and will not recover from that.

The following doesn't work anymore

```scala
Source.single("Ping".getBytes)
      .map(elem => new ProducerRecord[Array[Byte], Array[Byte]](consumerTopic, elem))
      .to(Producer.plainSink(producerSettings)).run()
```

**Comment by patriknw** [comment] 2016-04-11 15:40
thanks

**Comment by patriknw** [comment] 2016-04-12 08:35
@brunofitas I can't reproduce the issue. Tried exactly your code. Used a consumer:
```scala
      Consumer.plainSource(consumerSettings)
        .map(println)
        .runWith(Sink.ignore)
```

arrays are emitted by println, also for the published string.

**Comment by patriknw** [comment] 2016-04-12 08:43
I found another way to reproduce a maybe related issue. I created a topic with `StringSerializer` and then used an `IntegerDeserializer` for the consumer, and published strings. Then I see this in the log, repeated over and over:
```
10:39:06.933 ERROR o.apache.kafka.clients.NetworkClient - Uncaught error in request completion:
org.apache.kafka.common.errors.SerializationException: Size of data received by IntegerDeserializer is not 4
```

I don't know what to do about that.

Note that topics are auto-created on the first send, and it looks like that initialization matters for the type of topic. That is why the `IntegrationSpec` is setup like: https://github.com/akka/reactive-kafka/blob/master/core/src/test/scala/akka/kafka/scaladsl/IntegrationSpec.scala#L63

**Comment by brunofitas** [comment] 2016-04-12 13:24
I didn't want to complicate, so I used "Ping".getBytes() in the example. It looks like that is written in the same way on the kafka_topic than the string. I assumed it was going to fail. 
In my code, I'm getting the byteArray from an avroRecord, and if I send anything else to the topic, it crashes the consumer, even before trying to de-serialize it. Nothing gets to the consumer and there is no warning. I also tried sending a string directly from the"kafka-console-consumer.sh" and I had the same results.

**Comment by brunofitas** [comment] 2016-04-12 17:33
Ok, I was feeding Strings into a custom deserializer ArrayByte to case class with Avro and I was having a "java.io.EOFException" in silence.  Any errors inside  Consumer.atMostOnceSource(consumerSettings.withClientId(topic)).runForeach(m => { ... }) were passing unnoticed and made the consumer crash without warning. 
"CommittableMessage.value" has always the consumer deserializer type, even if the original message was not of that data type so we cannot really tell what was the original data type.
For custom deserializers, like Array[Byte] to case class, one can implement a try catch,  but even then, I have had strange results when feeding them with wrong data types. 
I'm not sure how if this can be achieved, but it would be great if the consumer could filter kafka messages where (kafka_message type == Deserializer type == CommittableMessage.value type)

**Comment by patriknw** [comment] 2016-04-13 06:49
I'm not sure we can do anything about this. At least in the example I used with Integer it was captured before reaching our consumer. We should look into this more, but it doesn't feel urgent. Any help is welcome.

**Comment by tdrozdowski** [comment] 2016-05-05 22:19
So I'm running into this issue as well.  In my case, I have a specialized serialize that serializes into case class via JSON (using Spray-JSON).  Works great - until someone puts some garbage data into the topic.  Then its an infinite loop as the poller keeps trying to deserialize the garbage into my code, which explodes.  I've played with a few ways in which to trap this error - but I keep winding up on a slippery slope of wrapping things with Either or Option - which complicates things further in the flow as you're working with the message.

I'm not sure that you could remove the message at the point - but somehow dealing with it and not getting stuck into this infinite loop/spam very second would be nice.  A serializer error timeout or something?

**Comment by patriknw** [comment] 2016-05-10 10:15
I acknowledge that this is problem, but I don't know how to solve it, so suggestions are welcome.

**Comment by 13h3r** [comment] 2016-07-04 09:00
Should we treat this as misconfiguration and jst fail in runtime because we have no ways to deal with it. 

We can not drop messages because we want to indicate that there is some error happens. Also all this functionality can be easily done in userland by getting `Array[Byte]` and reacting on parsing error.

My position is to close this. WDYT, @kciesielski @patriknw @drewhk

**Comment by 13h3r** [comment] 2016-08-16 11:23
Any thoughts? My position is to close this.

**Comment by kciesielski** [comment] 2016-08-16 11:26
+1, let's reopen if this issue pops up more often for more users.

**Comment by patriknw** [comment] 2016-08-16 15:22
+1

**Closed by patriknw** 2016-08-16 15:22 UTC
Labels: new-api
